#             __       _____                                      ___ _           _
#  __  __ /\ \ \___   \_   \_ __  ___  ___  ___ _   _ _ __ ___  / __\ |__   __ _| |_
#  \ \/ //  \/ / _ \   / /\/ '_ \/ __|/ _ \/ __| | | | '__/ _ \/ /  | '_ \ / _` | __|    Plugin by
#   >  </ /\  / (_) /\/ /_ | | | \__ \  __/ (__| |_| | | |  __/ /___| | | | (_| | |_     xPlugins
#  /_/\_\_\ \/ \___/\____/ |_| |_|___/\___|\___|\__,_|_|  \___\____/|_| |_|\__,_|\__|
#
#           Es Open Source: https://github.com/WilfryDev/xNoInsecureChat
#                      Discord: https://discord.xplugins.site
#
# Activa o desactiva la funci칩n principal del plugin.
# Si es 'true', se bloquear치n los mensajes de "chat no seguro".
# Si es 'false', el plugin no har치 nada y los mensajes aparecer치n.
enabled: true